name: Create Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: windows-latest
    name: Build and Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install
        run:
          pip install -e .[dev]

      - name: Build
        run:
          py tools\create_release.py

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: dist/*
          file_glob: true
          overwrite: true
          draft: true
